import { headers } from 'next/headers'

/**
 * Get the CSP nonce from request headers
 * This nonce is generated by middleware.ts and used to allow specific inline scripts
 *
 * @returns The nonce string or undefined if not available
 */
export async function getNonce(): Promise<string | undefined> {
  const headersList = await headers()
  return headersList.get('x-nonce') ?? undefined
}
